### PR TITLE
Add support for VoxelNeXt

### PR DESCRIPTION
**Pull request by yukang2017**
Hi, 

This is a pull request for [VoxelNeXt](https://arxiv.org/abs/2303.11301). VoxelNeXt is a simple, and fully-sparse 3D object detector. The core idea is to predict objects directly upon sparse voxel features. This work has been accepted by CVPR 2023.

For this pull request, it contains 
(1) backbone, head, detector in `pcdet/models`.
(2) argoverse2 dataset in `pcdet/datasets`.
(3) config files for nuScenes/Waymo/Argoverse2 datasets in `tools/cfgs`.
(4) updated README that includes the introduction of VoxelNeXt.
(5) some sparse loss functions in `pcdet/utils/loss_utils.py`.
(6) some utils in `pcdet/models/model_utils/centernet_utils.py`.

I have already tested both inference and training upon this code. Please feel free to contact me if there are any issues.

Regards,
Yukang Chen

### CODE REVIEW

**Comment by malicd** [comment]
Code for data preparation is [here](https://github.com/dvlab-research/VoxelNeXt/tree/master/argoverse2) and respective documentation is [here](https://github.com/dvlab-research/VoxelNeXt/blob/master/argoverse2/Argoverse2.md). Thanks for the amazing work!

**Comment by jihanyang** [comment]
@malicd Thank you for your reminder. We will also include these documentations in pcdet. Thanks Yukang @yukang2017 .

**Comment by yukang2017** [comment]
@malicd Thanks. We will merge them soon.

**Comment by yukang2017** [comment]
Note that it seems that there are some bugs for training VoxelNeXt on spconv 2.2/2.3 version. We are trying to fix it. Before we finish this, please use spconv in 2.1, e.g., spconv==2.1.25 for training!

**Comment by ryanyej** [comment]
Did this question solved?

**Pull request merged**
